# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ocALBKhNzcwClFlpgY5RU-dPMtj2zBG
"""

a,b= 10,20
print(a+b)
