# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CslCAJOLJDo7OX-6UTT0CMZTcMyMpnuL
"""

n=6
 print(n*n)
