# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18e9xTH6GeWXH5z9nOCNKiZeAGyoYtCcy
"""

#include <stdio.h>

int factorial(int n) {
    if (n == 0 || n == 1) {
        return 1;
    }

    return n * factorial(n - 1);
}

int main() {
    int n;

    printf("Enter a number: ");
    scanf("%d", &n);

    if (n < 0) {
        printf("Factorial is not defined for negative numbers.\n");
    } else {
        printf("Factorial of %d = %d\n", n, factorial(n));
    }

    return 0;
}

"""First, let's save your C code into a `.c` file using the `%%writefile` magic command."""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile factorial.c
# #include <stdio.h>
# 
# int factorial(int n) {
#     if (n == 0 || n == 1) {
#         return 1;
#     }
# 
#     return n * factorial(n - 1);
# }
# 
# int main() {
#     int n;
# 
#     printf("Enter a number: ");
#     scanf("%d", &n);
# 
#     if (n < 0) {
#         printf("Factorial is not defined for negative numbers.\n");
#     } else {
#         printf("Factorial of %d = %d\n", n, factorial(n));
#     }
# 
#     return 0;
# }

"""Next, we will compile the C code using `gcc`. We'll output the executable to a file named `factorial_program`."""

!gcc factorial.c -o factorial_program

"""Now, you can run the compiled program. Note that interactive input (like `scanf`) in Colab cells can be tricky. For demonstration, I will provide a fixed input, e.g., 5. If you want to change the input, you would need to modify this cell and run it again."""

# To run the program and provide input, you can use a pipe.
# For example, to calculate the factorial of 5:
!echo 5 | ./factorial_program

"""### Python Version of the Factorial Code"""

def factorial_python(n):
    if n == 0 or n == 1:
        return 1
    return n * factorial_python(n - 1)

def main_python():
    try:
        n = int(input("Enter a number: "))
        if n < 0:
            print("Factorial is not defined for negative numbers.")
        else:
            print(f"Factorial of {n} = {factorial_python(n)}")
    except ValueError:
        print("Invalid input. Please enter an integer.")

# Run the Python main function
main_python()

"""### Comparison between C and Python Factorial Implementations

Let's compare the C and Python versions based on the criteria you provided:

#### 1. Type Declaration

*   **C:** C is a statically typed language, meaning you must explicitly declare the data type for every variable and function parameter before using them. For example, `int n;` or `int factorial(int n)`. This helps the compiler perform type checking at compile time.

    ```c
    int factorial(int n) { // 'int' for return type and parameter type
        // ...
    }
    int n; // 'int' for variable n
    ```

*   **Python:** Python is a dynamically typed language. You do not need to explicitly declare data types. The interpreter infers the type of a variable at runtime based on the value assigned to it. This makes the code more concise but shifts type checking to runtime.

    ```python
    def factorial_python(n): # No type declarations for 'n'
        # ...
    
n = int(input("Enter a number: ")) # Type of 'n' is determined by the assigned value
    ```

#### 2. Block Structure

*   **C:** C uses curly braces `{}` to define code blocks for functions, conditional statements (`if`, `else`), and loops. Semicolons `;` are used to terminate statements.

    ```c
    int main() {
        if (n < 0) {
            printf("Factorial is not defined...\n");
        } else {
            printf("Factorial of %d = %d\n", n, factorial(n));
        }
        return 0;
    }
    ```

*   **Python:** Python uses indentation (whitespace) to define code blocks. There are no curly braces or semicolons (unless you put multiple statements on one line, which is generally discouraged for readability). This enforces a consistent and readable code style.

    ```python
    def main_python():
        if n < 0: # Colon indicates start of block
            print("Factorial is not defined...") # Indented block
        else:
            print(f"Factorial of {n} = {factorial_python(n)}") # Indented block
    ```

#### 3. Memory Handling

*   **C:** C provides low-level memory management. Programmers are responsible for explicitly allocating and deallocating memory using functions like `malloc()`, `calloc()`, and `free()`. This offers fine-grained control and can lead to highly optimized code, but also introduces risks like memory leaks or segmentation faults if not managed carefully.

    The factorial example doesn't explicitly use dynamic memory allocation, but in general C requires manual memory management.

*   **Python:** Python handles memory management automatically through a process called garbage collection. Programmers don't typically need to worry about allocating or deallocating memory. When an object is no longer referenced, Python's garbage collector automatically reclaims the memory. This simplifies development and reduces memory-related errors, though it can come with a slight performance overhead compared to finely tuned C code.

#### 4. Grouping Data (Data Structures)

*   **C:** C provides basic data grouping mechanisms primarily through `struct` and `union`. `struct` allows you to group variables of different data types into a single unit. Arrays are used for collections of elements of the same type.

    ```c
    struct Person {
        char name[50];
        int age;
    };
    // To use:
    struct Person p1;
    ```

*   **Python:** Python offers a rich set of built-in data structures for grouping data, including lists, tuples, dictionaries, and sets. These are powerful and flexible, supporting various operations directly. Python also has classes for creating custom objects, which encapsulate both data and behavior.

    ```python
    # List
    my_list = [1, 2, 3]

    # Dictionary
    my_dict = {'name': 'Alice', 'age': 30}

    # Class (Object-Oriented Programming)
    class Person:
        def __init__(self, name, age):
            self.name = name
            self.age = age
    # To use:
    p1 = Person('Alice', 30)
    ```
"""